# Generated by Django 5.0.7 on 2024-08-10 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='genre',
        ),
        migrations.DeleteModel(
            name='MovieGenre',
        ),
    ]
