# Generated by Django 5.0.7 on 2024-08-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_movies_genre_delete_moviegenre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='link',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
