# Generated by Django 5.0.7 on 2024-08-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_moviegenre_movies_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='genre',
            field=models.ManyToManyField(related_name='movies', to='base.moviegenre'),
        ),
    ]
